# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hW1vdMdPjTI6Fq6afHzVoNWODeBoVNai
"""

import joblib
import streamlit as st
import pandas as pd
import numpy as np
import base64
import seaborn as sns
import matplotlib.pyplot as plt

st.title("Predict Time to Deliver")

def user_input_features():
    sm_zone = st.sidebar.selectbox('Market Zone',('LATAM','NAM','GCHN','SOCO','CAR','RUB','CEA','EEU','MEWA','SECA','SA','EU','AUZ','SEA'))
    cust_country = st.sidebar.selectbox('Customer country',('Albania','Argentina','Australia','Austria','Bahrain','Belgium','Brazil','Brunei Darussalam','Bulgaria','Canada','China','Colombia',
'Costa Rica','Croatia','Cyprus','Czechia','Denmark','Dominican Republic','Ecuador','Estonia','Finland','France','Germany','Greece',
'Hong Kong','Hungary','India','Indonesia','Iraq','Ireland','Israel','Italy','Jamaica','Japan','Jordan','Kuwait','Latvia','Lebanon',
'Lithuania','Malaysia','Malta','Mexico','Myanmar','Nepal','Netherlands','New Zealand','Norway','Oman','Pakistan','Palestine State',
'Panama','Philippines','Poland','Portugal','Puerto Rico','Qatar','Romania','Russian Federation','Saudi Arabia','Serbia','Singapore',
'Slovakia','Slovenia','South Africa','South Korea','Spain','Sri Lanka','Sweden','Switzerland','Taiwan','Thailand','Trinidad and Tobago',
'Turkey','United Arab Emirates','United Kingdom','United States','Uruguay','Vietnam','Yemen'))
    cust_seg = st.sidebar.selectbox('Customer segment',('1','2','3','4','5'))
    MOT = st.sidebar.selectbox('Mode of Transport',('Air Direct','Truck FTL','Truck LTL','Vessel'))
    facility_id = st.sidebar.selectbox('Manufacturing facility',('CN07-Shanghai','CR02-Alajeula','ES01-Madrid','GR10-Hamburg','IN9A-Chakan','NL90-Best','PL01-Alges','PR01-San Juan','US09-Reedsville',
'US15-Andover','US17-Cleaveland','US19-Bothell','US20-Rancho Cordova','US21-Gainesville'))
    facility_country = st.sidebar.selectbox('Country of Manufacture',('United States','Netherlands','India','Germany','Costa Rico',
'Portugal','China','Spain','Peurto Rico'))
    prdt_cat = st.sidebar.selectbox('Product Category',('AMI','IGT','PD','AC','CAN'))
    prdt_code = st.sidebar.selectbox('Product Code',('347','348','349','350','351','352','353','354','424','425','426','427','428','429','430',
                                                     '629','630','631','632','633','634','635','821','822','823','824','825','876','877','878','879','880','881'))
    prdt_seg = st.sidebar.selectbox('Product segment',('cat1','cat2','cat3','cat4','cat5'))
    order_week=st.sidebar.selectbox('Week likely to place order',('1','2','3','4','5'))
    order_month=st.sidebar.selectbox('Month likely to place order',('1','2','3','4','5','6','7','8','9','10','11','12'))

    data = {'cust_seg':[cust_seg], 
            'cust_country':[cust_country],
            'sm_zone':[sm_zone], 
            'MOT':[MOT], 
            'facility_id':[facility_id], 
            'facility_country':[facility_country], 
            'prdt_code':[prdt_code],
            'prdt_cat':[prdt_cat], 
            'prdt_seg':[prdt_seg], 
            'order_week':[order_week], 
            'order_month':[order_month], 
            }
    features = pd.DataFrame(data)
    return features

input_df = user_input_features()
# Commented out IPython magic to ensure Python compatibility.
def predict(data):
    #col = ['cust_seg','cust_country','sm_zone','MOT','facility_id','facility_country','prdt_code','prdt_cat','prdt_seg','order_month','order_week']
    #data = pd.get_dummies(data=data, columns=col)
    clf = joblib.load("model.sav")
    return clf.predict(data)

if st.button("Predict Time to deliver this order"):
    result = predict(input_df)
    st.text(np.round(result[0],0))

